rpc: "http://127.0.0.1:26294"
api: "http://127.0.0.1:1389"
bech_32_prefix: "0g"
batch_size: 150
start_height: 1564327
log_lvl: "INFO"

metrics:
  jails: true
  delegators: false
  tombstones: true
