rpc: "https://rpc-zero-gravity-testnet.trusted-point.com:443"
api: "https://api-zero-gravity-testnet.trusted-point.com:443"
bech_32_prefix: "evmos"
stake_denom: "aevmos"
chain_id: "zgtendermint_9000-1"
